patchedDependencies:
  metal-fx@2.0.11: patches/metal-fx@2.0.11.patch
allowBuilds:
  esbuild: true
overrides:
  '@pierre/trees>@pierre/theming': 1.0.1
minimumReleaseAgeExclude:
  - '@modelcontextprotocol/client@2.2.0'
  - '@modelcontextprotocol/core@2.2.0'
  - '@modelcontextprotocol/server@2.2.0'
  - '@pierre/diffs@1.5.1'
  - nodemailer@10.0.12
